"""Report generation in JSON, HTML, and terminal formats."""

from __future__ import annotations

import dataclasses
import json
from pathlib import Path
from typing import TYPE_CHECKING

from jinja2 import Template

from dockpulse.dashboard import Dashboard

if TYPE_CHECKING:
    from dockpulse.models import WasteReport

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>DockPulse Waste Report</title>
<style>
  :root { --bg: #0f172a; --surface: #1e293b; --border: #334155;
          --text: #e2e8f0; --accent: #38bdf8; --danger: #ef4444;
          --success: #22c55e; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
         sans-serif; background: var(--bg); color: var(--text); padding: 2rem; }
  h1 { font-size: 1.75rem; margin-bottom: .25rem; }
  .subtitle { color: #94a3b8; margin-bottom: 2rem; }
  .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
             gap: 1rem; margin-bottom: 2rem; }
  .card { background: var(--surface); border: 1px solid var(--border);
          border-radius: .5rem; padding: 1.25rem; }
  .card .label { font-size: .75rem; text-transform: uppercase; letter-spacing: .05em;
                 color: #94a3b8; margin-bottom: .25rem; }
  .card .value { font-size: 1.5rem; font-weight: 700; }
  .card .value.danger { color: var(--danger); }
  .card .value.success { color: var(--success); }
  table { width: 100%; border-collapse: collapse; background: var(--surface);
          border-radius: .5rem; overflow: hidden; }
  th { background: var(--border); text-align: left; padding: .75rem 1rem;
       font-size: .75rem; text-transform: uppercase; letter-spacing: .05em; }
  td { padding: .75rem 1rem; border-bottom: 1px solid var(--border); }
  tr:last-child td { border-bottom: none; }
  .tag { display: inline-block; padding: .125rem .5rem; border-radius: 9999px;
         font-size: .75rem; font-weight: 600; }
  .tag-save { background: rgba(34,197,94,.15); color: var(--success); }
  .tag-none { background: rgba(148,163,184,.15); color: #94a3b8; }
  footer { margin-top: 2rem; text-align: center; color: #64748b; font-size: .8rem; }
</style>
</head>
<body>
<h1>DockPulse Waste Report</h1>
<p class="subtitle">Container resource analysis and right-sizing recommendations</p>

<div class="summary">
  <div class="card">
    <div class="label">Memory Allocated</div>
    <div class="value">{{ "%.0f"|format(report.total_memory_allocated_mb) }} MB</div>
  </div>
  <div class="card">
    <div class="label">Memory Used (p95)</div>
    <div class="value">{{ "%.0f"|format(report.total_memory_used_p95_mb) }} MB</div>
  </div>
  <div class="card">
    <div class="label">Memory Waste</div>
    <div class="value danger">{{ "%.0f"|format(report.total_memory_waste_mb) }} MB
      ({{ "%.1f"|format(report.waste_percentage) }}%)</div>
  </div>
  <div class="card">
    <div class="label">CPU Waste</div>
    <div class="value danger">{{ "%.2f"|format(report.total_cpu_waste) }} cores</div>
  </div>
</div>

<table>
<thead>
<tr>
  <th>Container</th>
  <th>Current Mem</th>
  <th>Recommended Mem</th>
  <th>Savings</th>
  <th>Current CPU</th>
  <th>Recommended CPU</th>
  <th>Headroom</th>
</tr>
</thead>
<tbody>
{% for rec in report.recommendations %}
<tr>
  <td><strong>{{ rec.container_name }}</strong></td>
  <td>{{ "%.0f MB"|format(rec.current_memory_limit_mb) if rec.current_memory_limit_mb > 0 else "none" }}</td>
  <td>{{ "%.0f MB"|format(rec.recommended_memory_limit_mb) }}</td>
  <td>
    {% if rec.memory_savings_mb > 0 %}
      <span class="tag tag-save">-{{ "%.0f"|format(rec.memory_savings_mb) }} MB</span>
    {% else %}
      <span class="tag tag-none">--</span>
    {% endif %}
  </td>
  <td>{{ "%.2f"|format(rec.current_cpu_limit) if rec.current_cpu_limit > 0 else "none" }}</td>
  <td>{{ "%.2f"|format(rec.recommended_cpu_limit) }}</td>
  <td>{{ "%.0f"|format(rec.headroom_percent) }}%</td>
</tr>
{% endfor %}
</tbody>
</table>

<footer>Generated by DockPulse &mdash; Container Resource Profiler &amp; Right-Sizer</footer>
</body>
</html>
"""


class Reporter:
    """Generates waste reports in multiple output formats."""

    def to_json(self, report: WasteReport, path: str) -> None:
        """Serialise the waste report to a JSON file.

        Args:
            report: The waste report to serialise.
            path: Destination file path.
        """
        data = dataclasses.asdict(report)
        data["waste_percentage"] = report.waste_percentage

        dest = Path(path)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(json.dumps(data, indent=2, default=str))

    def to_html(self, report: WasteReport, path: str) -> None:
        """Render the waste report as a styled HTML page.

        Args:
            report: The waste report to render.
            path: Destination file path.
        """
        template = Template(_HTML_TEMPLATE)
        html = template.render(report=report)

        dest = Path(path)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(html)

    def to_terminal(self, report: WasteReport) -> None:
        """Print the waste report to the terminal using Rich."""
        Dashboard().render_waste_report(report)
