"""Interactive HTML report generation with Plotly charts."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

import plotly.graph_objects as go
from plotly.subplots import make_subplots

if TYPE_CHECKING:
    from dockpulse.models import HistoricalComparison, ProfileResult, StackAnalysis

# ---------------------------------------------------------------------------
# DockPulse brand palette
# ---------------------------------------------------------------------------
_BG = "#0f172a"
_SURFACE = "#1e293b"
_PRIMARY = "#38bdf8"
_SUCCESS = "#22c55e"
_DANGER = "#ef4444"
_WARNING = "#f59e0b"
_TEXT = "#e2e8f0"
_MUTED = "#94a3b8"
_BORDER = "#334155"

_CHART_COLORS = [_PRIMARY, _SUCCESS, _WARNING, _DANGER, "#a78bfa", "#fb923c", "#2dd4bf"]

_PLOTLY_LAYOUT_DEFAULTS: dict = dict(
    paper_bgcolor=_SURFACE,
    plot_bgcolor=_BG,
    font=dict(family="Inter, system-ui, sans-serif", color=_TEXT, size=13),
    margin=dict(l=60, r=30, t=50, b=50),
    legend=dict(bgcolor="rgba(0,0,0,0)", borderwidth=0),
    xaxis=dict(gridcolor=_BORDER, zerolinecolor=_BORDER),
    yaxis=dict(gridcolor=_BORDER, zerolinecolor=_BORDER),
)

# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------
_HTML_WRAPPER = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<script src="https://cdn.plot.ly/plotly-2.32.0.min.js" charset="utf-8"></script>
<style>
  :root {{
    --bg: {bg}; --surface: {surface}; --border: {border};
    --text: {text}; --accent: {primary};
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: var(--bg); color: var(--text); padding: 2rem 3rem;
    min-height: 100vh;
  }}
  .dp-header {{
    display: flex; align-items: center; gap: 1rem;
    margin-bottom: .5rem;
  }}
  .dp-header h1 {{
    font-size: 1.75rem; font-weight: 800;
    background: linear-gradient(135deg, {primary}, {success});
    -webkit-background-clip: text; -webkit-text-fill-color: transparent;
  }}
  .dp-meta {{
    color: {muted}; font-size: .85rem; margin-bottom: 2rem;
  }}
  .dp-section {{
    background: var(--surface); border: 1px solid var(--border);
    border-radius: .75rem; padding: 1.5rem; margin-bottom: 1.5rem;
  }}
  .dp-section h2 {{
    font-size: 1.1rem; font-weight: 600; margin-bottom: 1rem;
    color: var(--accent);
  }}
  .dp-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; }}
  @media (max-width: 900px) {{ .dp-grid {{ grid-template-columns: 1fr; }} }}
  footer {{
    margin-top: 2rem; text-align: center; color: {muted}; font-size: .8rem;
  }}
</style>
</head>
<body>
<div class="dp-header">
  <h1>DockPulse</h1>
</div>
<p class="dp-meta">{subtitle}<br>Generated {timestamp}</p>
{body}
<footer>Generated by DockPulse &mdash; Container Resource Profiler &amp; Right-Sizer</footer>
</body>
</html>
"""


def _apply_layout(fig: go.Figure, **overrides: object) -> go.Figure:
    """Apply the DockPulse dark theme to a Plotly figure."""
    merged = {**_PLOTLY_LAYOUT_DEFAULTS, **overrides}
    fig.update_layout(**merged)
    return fig


def _fig_to_div(fig: go.Figure) -> str:
    """Render a Plotly figure as an embeddable ``<div>``."""
    return fig.to_html(full_html=False, include_plotlyjs=False)


def _wrap_html(title: str, subtitle: str, body: str) -> str:
    return _HTML_WRAPPER.format(
        title=title,
        subtitle=subtitle,
        timestamp=datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        body=body,
        bg=_BG,
        surface=_SURFACE,
        border=_BORDER,
        text=_TEXT,
        primary=_PRIMARY,
        success=_SUCCESS,
        muted=_MUTED,
    )


def _write(html: str, output_path: str) -> None:
    dest = Path(output_path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(html)


# ===================================================================
# Visualizer
# ===================================================================


class Visualizer:
    """Generates interactive HTML reports with Plotly charts."""

    # ------------------------------------------------------------------
    # Profile report
    # ------------------------------------------------------------------

    def generate_profile_report(
        self,
        profiles: list[ProfileResult],
        output_path: str,
    ) -> None:
        """Generate a comprehensive HTML report with interactive charts.

        Charts included:
        1. CPU usage over time (line chart per container with p95 threshold)
        2. Memory usage over time (line chart per container with limit line)
        3. Resource allocation vs actual usage (grouped bar chart)
        4. Resource waste breakdown (pie chart)
        5. Container comparison radar chart
        """
        charts: list[str] = []
        charts.append(self._chart_cpu_over_time(profiles))
        charts.append(self._chart_memory_over_time(profiles))
        charts.append(self._chart_allocation_vs_actual(profiles))
        charts.append(self._chart_waste_pie(profiles))
        charts.append(self._chart_radar(profiles))

        grid_html = '<div class="dp-grid">'
        for i, chart in enumerate(charts):
            grid_html += f'<div class="dp-section">{chart}</div>'
            if i == 1:
                grid_html += "</div>"
                grid_html += '<div class="dp-grid">'
        grid_html += "</div>"

        html = _wrap_html(
            title="DockPulse — Profile Report",
            subtitle=f"Profiling report for {len(profiles)} container(s)",
            body=grid_html,
        )
        _write(html, output_path)

    # ------------------------------------------------------------------
    # Comparison report
    # ------------------------------------------------------------------

    def generate_comparison_report(
        self,
        comparisons: list[HistoricalComparison],
        output_path: str,
    ) -> None:
        """Generate a comparison report between two profiling sessions.

        Charts:
        1. CPU p95 delta per container (horizontal bar, red/green)
        2. Memory p95 delta per container (horizontal bar, red/green)
        3. Trend summary (donut chart: increasing/decreasing/stable counts)
        """
        charts: list[str] = []
        charts.append(self._chart_cpu_delta(comparisons))
        charts.append(self._chart_memory_delta(comparisons))
        charts.append(self._chart_trend_donut(comparisons))

        body = '<div class="dp-grid">'
        for chart in charts[:2]:
            body += f'<div class="dp-section">{chart}</div>'
        body += "</div>"
        body += f'<div class="dp-section">{charts[2]}</div>'

        session_a = comparisons[0].session_a_id[:8] if comparisons else "?"
        session_b = comparisons[0].session_b_id[:8] if comparisons else "?"

        html = _wrap_html(
            title="DockPulse — Comparison Report",
            subtitle=f"Session {session_a} vs {session_b} &mdash; {len(comparisons)} container(s)",
            body=body,
        )
        _write(html, output_path)

    # ------------------------------------------------------------------
    # Stack report
    # ------------------------------------------------------------------

    def generate_stack_report(
        self,
        stack: StackAnalysis,
        output_path: str,
    ) -> None:
        """Generate a stack analysis report.

        Charts:
        1. Resource pressure heatmap (services x metrics)
        2. Service ranking bar chart
        3. Memory utilization gauge per service
        """
        charts: list[str] = []
        charts.append(self._chart_pressure_heatmap(stack))
        charts.append(self._chart_service_ranking(stack))
        charts.append(self._chart_memory_gauges(stack))

        body = f'<div class="dp-section">{charts[0]}</div>'
        body += '<div class="dp-grid">'
        body += f'<div class="dp-section">{charts[1]}</div>'
        body += f'<div class="dp-section">{charts[2]}</div>'
        body += "</div>"

        html = _wrap_html(
            title="DockPulse — Stack Analysis",
            subtitle=(
                f"Stack with {len(stack.profiles)} service(s) &mdash; "
                f"Bottleneck: {stack.bottleneck} ({stack.bottleneck_reason})"
            ),
            body=body,
        )
        _write(html, output_path)

    # ==================================================================
    # Profile chart builders
    # ==================================================================

    def _chart_cpu_over_time(self, profiles: list[ProfileResult]) -> str:
        fig = go.Figure()
        for idx, p in enumerate(profiles):
            color = _CHART_COLORS[idx % len(_CHART_COLORS)]
            timestamps = [s.timestamp for s in p.samples]
            cpus = [s.cpu_percent for s in p.samples]
            fig.add_trace(go.Scatter(
                x=timestamps,
                y=cpus,
                mode="lines",
                name=p.name,
                line=dict(color=color, width=2),
                hovertemplate="%{y:.1f}%<extra>%{fullData.name}</extra>",
            ))
            fig.add_hline(
                y=p.cpu_p95,
                line_dash="dash",
                line_color=color,
                opacity=0.5,
                annotation_text=f"p95 {p.name}",
                annotation_font_size=10,
                annotation_font_color=_MUTED,
            )
        _apply_layout(
            fig,
            title=dict(text="CPU Usage Over Time", font=dict(size=15)),
            xaxis_title="Time",
            yaxis_title="CPU %",
            height=380,
        )
        return _fig_to_div(fig)

    def _chart_memory_over_time(self, profiles: list[ProfileResult]) -> str:
        fig = go.Figure()
        for idx, p in enumerate(profiles):
            color = _CHART_COLORS[idx % len(_CHART_COLORS)]
            timestamps = [s.timestamp for s in p.samples]
            mems = [s.memory_usage_mb for s in p.samples]
            fig.add_trace(go.Scatter(
                x=timestamps,
                y=mems,
                mode="lines",
                name=p.name,
                line=dict(color=color, width=2),
                hovertemplate="%{y:.1f} MB<extra>%{fullData.name}</extra>",
            ))
            if p.memory_limit_mb > 0:
                fig.add_hline(
                    y=p.memory_limit_mb,
                    line_dash="dot",
                    line_color=_DANGER,
                    opacity=0.6,
                    annotation_text=f"limit {p.name}",
                    annotation_font_size=10,
                    annotation_font_color=_DANGER,
                )
        _apply_layout(
            fig,
            title=dict(text="Memory Usage Over Time", font=dict(size=15)),
            xaxis_title="Time",
            yaxis_title="Memory (MB)",
            height=380,
        )
        return _fig_to_div(fig)

    def _chart_allocation_vs_actual(self, profiles: list[ProfileResult]) -> str:
        names = [p.name for p in profiles]
        allocated_mem = [p.memory_limit_mb for p in profiles]
        actual_mem = [p.memory_p95_mb for p in profiles]
        allocated_cpu = [p.peak_cpu for p in profiles]
        actual_cpu = [p.cpu_p95 for p in profiles]

        fig = make_subplots(
            rows=1, cols=2,
            subplot_titles=("Memory (MB)", "CPU (%)"),
            horizontal_spacing=0.15,
        )

        fig.add_trace(go.Bar(
            x=names, y=allocated_mem, name="Allocated",
            marker_color=_MUTED, opacity=0.6,
            hovertemplate="%{y:.0f} MB<extra>Allocated</extra>",
        ), row=1, col=1)
        fig.add_trace(go.Bar(
            x=names, y=actual_mem, name="Actual (p95)",
            marker_color=_PRIMARY,
            hovertemplate="%{y:.1f} MB<extra>Actual p95</extra>",
        ), row=1, col=1)

        fig.add_trace(go.Bar(
            x=names, y=allocated_cpu, name="Peak",
            marker_color=_MUTED, opacity=0.6, showlegend=False,
            hovertemplate="%{y:.1f}%<extra>Peak</extra>",
        ), row=1, col=2)
        fig.add_trace(go.Bar(
            x=names, y=actual_cpu, name="p95",
            marker_color=_SUCCESS, showlegend=False,
            hovertemplate="%{y:.1f}%<extra>p95</extra>",
        ), row=1, col=2)

        _apply_layout(
            fig,
            title=dict(text="Resource Allocation vs Actual Usage", font=dict(size=15)),
            barmode="group",
            height=380,
        )
        fig.update_annotations(font_color=_MUTED)
        return _fig_to_div(fig)

    def _chart_waste_pie(self, profiles: list[ProfileResult]) -> str:
        labels: list[str] = []
        waste_values: list[float] = []

        for p in profiles:
            mem_waste = max(p.memory_limit_mb - p.memory_p95_mb, 0) if p.memory_limit_mb > 0 else 0
            if mem_waste > 0:
                labels.append(p.name)
                waste_values.append(mem_waste)

        if not labels:
            labels = ["No waste detected"]
            waste_values = [1]

        fig = go.Figure(go.Pie(
            labels=labels,
            values=waste_values,
            hole=0.45,
            marker=dict(
                colors=_CHART_COLORS[: len(labels)],
                line=dict(color=_BG, width=2),
            ),
            textinfo="label+percent",
            textfont=dict(size=12),
            hovertemplate="%{label}: %{value:.0f} MB (%{percent})<extra></extra>",
        ))
        _apply_layout(
            fig,
            title=dict(text="Memory Waste Breakdown", font=dict(size=15)),
            height=380,
            showlegend=False,
        )
        return _fig_to_div(fig)

    def _chart_radar(self, profiles: list[ProfileResult]) -> str:
        categories = ["CPU p95", "Memory p95", "Network RX", "Disk I/O", "PIDs"]

        fig = go.Figure()
        for idx, p in enumerate(profiles):
            net_rx = sum(s.network_rx_mb for s in p.samples) / max(len(p.samples), 1)
            disk_io = sum(s.block_read_mb + s.block_write_mb for s in p.samples) / max(len(p.samples), 1)
            avg_pids = sum(s.pids for s in p.samples) / max(len(p.samples), 1)

            values = [p.cpu_p95, p.memory_p95_mb, net_rx, disk_io, avg_pids]

            color = _CHART_COLORS[idx % len(_CHART_COLORS)]
            fig.add_trace(go.Scatterpolar(
                r=[*values, values[0]],
                theta=[*categories, categories[0]],
                fill="toself",
                fillcolor=color.replace(")", ",0.15)").replace("rgb", "rgba")
                if color.startswith("rgb")
                else color + "26",
                line=dict(color=color, width=2),
                name=p.name,
                hovertemplate="%{theta}: %{r:.2f}<extra>%{fullData.name}</extra>",
            ))

        _apply_layout(
            fig,
            title=dict(text="Container Comparison", font=dict(size=15)),
            polar=dict(
                bgcolor=_BG,
                radialaxis=dict(visible=True, gridcolor=_BORDER, color=_MUTED),
                angularaxis=dict(gridcolor=_BORDER, color=_TEXT),
            ),
            height=420,
        )
        return _fig_to_div(fig)

    # ==================================================================
    # Comparison chart builders
    # ==================================================================

    def _chart_cpu_delta(self, comparisons: list[HistoricalComparison]) -> str:
        names = [c.container_name for c in comparisons]
        deltas = [c.cpu_p95_delta for c in comparisons]
        colors = [_DANGER if d > 0 else _SUCCESS for d in deltas]

        fig = go.Figure(go.Bar(
            y=names,
            x=deltas,
            orientation="h",
            marker_color=colors,
            hovertemplate="%{x:+.1f}%<extra>%{y}</extra>",
            text=[f"{d:+.1f}%" for d in deltas],
            textposition="outside",
            textfont=dict(size=11),
        ))
        _apply_layout(
            fig,
            title=dict(text="CPU p95 Delta", font=dict(size=15)),
            xaxis_title="Change (%)",
            height=max(250, 50 * len(names)),
        )
        return _fig_to_div(fig)

    def _chart_memory_delta(self, comparisons: list[HistoricalComparison]) -> str:
        names = [c.container_name for c in comparisons]
        deltas = [c.memory_p95_delta_mb for c in comparisons]
        colors = [_DANGER if d > 0 else _SUCCESS for d in deltas]

        fig = go.Figure(go.Bar(
            y=names,
            x=deltas,
            orientation="h",
            marker_color=colors,
            hovertemplate="%{x:+.1f} MB<extra>%{y}</extra>",
            text=[f"{d:+.1f} MB" for d in deltas],
            textposition="outside",
            textfont=dict(size=11),
        ))
        _apply_layout(
            fig,
            title=dict(text="Memory p95 Delta", font=dict(size=15)),
            xaxis_title="Change (MB)",
            height=max(250, 50 * len(names)),
        )
        return _fig_to_div(fig)

    def _chart_trend_donut(self, comparisons: list[HistoricalComparison]) -> str:
        trends = {"increasing": 0, "decreasing": 0, "stable": 0}
        for c in comparisons:
            trends[c.cpu_trend] = trends.get(c.cpu_trend, 0) + 1
            trends[c.memory_trend] = trends.get(c.memory_trend, 0) + 1

        labels = list(trends.keys())
        values = list(trends.values())
        colors = [_DANGER, _SUCCESS, _WARNING]

        fig = go.Figure(go.Pie(
            labels=labels,
            values=values,
            hole=0.5,
            marker=dict(colors=colors, line=dict(color=_BG, width=2)),
            textinfo="label+value",
            textfont=dict(size=13),
            hovertemplate="%{label}: %{value} metric(s)<extra></extra>",
        ))
        _apply_layout(
            fig,
            title=dict(text="Trend Summary", font=dict(size=15)),
            height=350,
            showlegend=False,
        )
        return _fig_to_div(fig)

    # ==================================================================
    # Stack chart builders
    # ==================================================================

    def _chart_pressure_heatmap(self, stack: StackAnalysis) -> str:
        metrics = ["CPU p95 (%)", "Mem p95 (MB)", "Avg Net RX (MB)", "Avg Disk I/O (MB)", "Avg PIDs"]
        services = [p.name for p in stack.profiles]
        z: list[list[float]] = []

        for p in stack.profiles:
            net_rx = sum(s.network_rx_mb for s in p.samples) / max(len(p.samples), 1)
            disk_io = sum(s.block_read_mb + s.block_write_mb for s in p.samples) / max(len(p.samples), 1)
            avg_pids = sum(s.pids for s in p.samples) / max(len(p.samples), 1)
            z.append([p.cpu_p95, p.memory_p95_mb, net_rx, disk_io, avg_pids])

        fig = go.Figure(go.Heatmap(
            z=z,
            x=metrics,
            y=services,
            colorscale=[
                [0.0, _BG],
                [0.25, "#1e3a5f"],
                [0.5, _PRIMARY],
                [0.75, _WARNING],
                [1.0, _DANGER],
            ],
            hovertemplate="Service: %{y}<br>Metric: %{x}<br>Value: %{z:.2f}<extra></extra>",
            texttemplate="%{z:.1f}",
            textfont=dict(size=11, color=_TEXT),
        ))
        _apply_layout(
            fig,
            title=dict(text="Resource Pressure Heatmap", font=dict(size=15)),
            height=max(300, 60 * len(services)),
        )
        return _fig_to_div(fig)

    def _chart_service_ranking(self, stack: StackAnalysis) -> str:
        names = [r[0] for r in stack.service_rankings]
        scores = [r[1] for r in stack.service_rankings]
        colors = [
            _DANGER if s > 0.7 else (_WARNING if s > 0.4 else _SUCCESS) for s in scores
        ]

        fig = go.Figure(go.Bar(
            x=scores,
            y=names,
            orientation="h",
            marker_color=colors,
            hovertemplate="Score: %{x:.3f}<extra>%{y}</extra>",
            text=[f"{s:.3f}" for s in scores],
            textposition="outside",
            textfont=dict(size=11),
        ))
        _apply_layout(
            fig,
            title=dict(text="Service Ranking (Resource Pressure)", font=dict(size=15)),
            xaxis_title="Pressure Score",
            xaxis=dict(range=[0, max(scores, default=1) * 1.25], gridcolor=_BORDER, zerolinecolor=_BORDER),
            height=max(280, 55 * len(names)),
        )
        return _fig_to_div(fig)

    def _chart_memory_gauges(self, stack: StackAnalysis) -> str:
        n = len(stack.profiles)
        if n == 0:
            fig = go.Figure()
            _apply_layout(fig, title=dict(text="Memory Utilization", font=dict(size=15)), height=200)
            return _fig_to_div(fig)

        cols = min(n, 3)
        rows = (n + cols - 1) // cols
        fig = make_subplots(
            rows=rows,
            cols=cols,
            specs=[[{"type": "indicator"}] * cols for _ in range(rows)],
            horizontal_spacing=0.08,
            vertical_spacing=0.15,
        )

        for idx, p in enumerate(stack.profiles):
            r = idx // cols + 1
            c = idx % cols + 1
            utilization = (p.memory_p95_mb / p.memory_limit_mb * 100) if p.memory_limit_mb > 0 else 0

            fig.add_trace(
                go.Indicator(
                    mode="gauge+number",
                    value=utilization,
                    number=dict(suffix="%", font=dict(size=22)),
                    title=dict(text=p.name, font=dict(size=12, color=_TEXT)),
                    gauge=dict(
                        axis=dict(range=[0, 100], tickcolor=_MUTED),
                        bar=dict(color=_PRIMARY),
                        bgcolor=_BG,
                        borderwidth=1,
                        bordercolor=_BORDER,
                        steps=[
                            dict(range=[0, 50], color="#0f172a"),
                            dict(range=[50, 80], color="#1e3a5f"),
                            dict(range=[80, 100], color="rgba(239,68,68,0.25)"),
                        ],
                        threshold=dict(
                            line=dict(color=_DANGER, width=3),
                            thickness=0.8,
                            value=80,
                        ),
                    ),
                ),
                row=r,
                col=c,
            )

        _apply_layout(
            fig,
            title=dict(text="Memory Utilization by Service", font=dict(size=15)),
            height=max(280, 250 * rows),
        )
        return _fig_to_div(fig)
